# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-22 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_details',
            new_name='event_details',
        ),
    ]
