# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-23 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170622_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_details',
            name='link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
