# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-23 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_details_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='news_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
