# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-23 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_news_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_details',
            name='status',
            field=models.CharField(choices=[('1', 'Approved'), ('2', 'Not-Approved')], default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='news_details',
            name='status',
            field=models.CharField(choices=[('1', 'Approved'), ('2', 'Not-Approved')], default=1, max_length=1),
        ),
    ]
