# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-03 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20170630_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_details',
            name='details',
            field=models.CharField(max_length=500),
        ),
    ]
