# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-23 09:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170620_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='font',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
