# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-23 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_details_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='mode',
            field=models.CharField(choices=[('1', 'Daymode'), ('2', 'Nightmode')], default=1, max_length=1),
        ),
    ]
