# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-23 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170623_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='username',
            new_name='email',
        ),
    ]
